# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chester Ismay
email: chester@pacificu.edu
position:  Instructional Technologist
position2: Adjunct Professor
institution: Reed College
inst_link1: http://www.reed.edu
inst_link2: http://www.pacificu.edu
#description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ismayc.github.io" # the base hostname & protocol for your site
twitter_username: old_man_chester
github_username:  ismayc

# Build settings
markdown: kramdown